#
# Copyright Siemens AG, 2021. Part of the SW360 Portal Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

site_name: SW360 Docs
docs_dir: 'sw360docs'

theme:
  name: 'material'
  logo: 'img/logo.png'

extra_css:
  - stylesheets/extra.css

use_directory_urls: false

nav:
- Introduction: 'index.md'
- User Guide:
    - 'Login to SW360' : 'user-guide/login/login.md'
    - 'Components and Releases' : 'user-guide/component-and-releases/component-and-releases.md'
    - 'Projects' : 'user-guide/projects/projects.md'
    - 'Tasks for Experts' : 'user-guide/tasks-for-experts/tasks-for-experts.md'
- Administrator Guide:
    - 'User Management Roles' : 'administrator-guide/user-management-roles/user-management-roles.md'
    - 'Admin Menu' : 'administrator-guide/admin-menu/admin-menu.md'
    - 'Properties' : 'administrator-guide/properties/properties.md'
- Best Practices:
    - 'Component Naming' : 'sw360-best-practices/component-naming.md'
    - 'License Naming' : 'sw360-best-practices/license-naming.md'
    - 'Record Creation' : 'sw360-best-practices/good-record-creation-structure.md'
    - 'SW360 Best Practices' : 'sw360-best-practices/sw360-best-practices.md'
- RESTful API:
    - 'Introduction' : 'sw360-RESTful-API/introduction.md'
    - 'Access' : 'sw360-RESTful-API/access.md'
    - 'API Guide' : '/resource/docs/api-guide.html'
- FAQ: 'sw360-user-FAQ/sw360-user-FAQ.md'